[features]
seeds = false
skip-lint = false
[programs.devnet]
regov_vc = "6wxT8RjtniTfzBJr3tfgAAbpwZVWTeCMqbReJMqY5mGM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/varsha/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
